services:
  db:
    container_name: pg-docker
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my_network

  api:
    container_name: api
    build: ./api
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api/src
        target: /app/api/src
    networks:
      - my_network

  client:
    container_name: client
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./client/src
        target: /app/client/src
    networks:
      - my_network


volumes:
  db-data:

networks:
  my_network:
    driver: bridge