/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("events").del();
  await knex("events").insert([
    {
      name: "Smith Funeral",
      startTime: "12:00:00",
      endTime: "12:00:00",
      startDate: "2024-08-26",
      endDate: "2024-08-26",
      description: "RIP in Peace",
      type: "Funeral",
      approved: "true",
      location: "Denver",
      POCinfo: "John",
      creatorID: 1
    },
    {
      name: "Jones Retirement",
      startTime: "09:00:00",
      endTime: "10:00:00",
      startDate: "2024-08-28",
      endDate: "2024-08-28",
      description: "About time",
      type: "Retirement",
      approved: "false",
      location: "DC",
      POCinfo: "Jake",
      creatorID: 1
    },
    {
      name: "Ralph Nader Inaguration",
      startTime: "07:00:00",
      endTime: "16:00:00",
      startDate: "2025-01-20",
      endDate: "2025-01-20",
      description: "long day",
      type: "Inaguration",
      approved: "true",
      location: "Dover",
      POCinfo: "Ben",
      creatorID: 1
    },
    {
      name: "Surgery Recovery",
      startTime: "07:00:00",
      endTime: "16:00:00",
      startDate: "2025-01-20",
      endDate: "2025-01-20",
      description: "long day",
      type: "Request",
      approved: "true",
      location: "DC",
      POCinfo: "John",
      creatorID: 1
    },
    {
      name: "Tech Conference 2024",
      startTime: "09:00:00",
      endTime: "17:00:00",
      startDate: "2024-09-15",
      endDate: "2024-09-17",
      description: "Annual technology conference featuring keynote speakers and workshops",
      type: "Conference",
      approved: "true",
      location: "San Francisco",
      POCinfo: "Sarah Johnson",
      creatorID: 1
    },
    {
      name: "Community Garden Planting Day",
      startTime: "08:30:00",
      endTime: "14:00:00",
      startDate: "2024-04-22",
      endDate: "2024-04-22",
      description: "Join us for Earth Day as we plant new vegetables and flowers in the community garden",
      type: "Community Event",
      approved: "true",
      location: "Central Park",
      POCinfo: "Mike Chen",
      creatorID: 1
    },
    {
      name: "Annual Charity Gala",
      startTime: "19:00:00",
      endTime: "23:00:00",
      startDate: "2024-11-10",
      endDate: "2024-11-10",
      description: "Fundraising event for local children's hospital",
      type: "Fundraiser",
      approved: "true",
      location: "Grand Ballroom, Hilton Hotel",
      POCinfo: "Emily Wright",
      creatorID: 1
    },
    {
      name: "Summer Music Festival",
      startTime: "12:00:00",
      endTime: "23:00:00",
      startDate: "2024-07-20",
      endDate: "2024-07-22",
      description: "Three-day outdoor music festival featuring local and international artists",
      type: "Concert",
      approved: "true",
      location: "Riverfront Park",
      POCinfo: "David Lee",
      creatorID: 1
    },
    {
      name: "Virtual Book Club Meeting",
      startTime: "19:30:00",
      endTime: "21:00:00",
      startDate: "2024-06-05",
      endDate: "2024-06-05",
      description: "Online discussion of this month's selected novel",
      type: "Club Meeting",
      approved: "true",
      location: "Zoom",
      POCinfo: "Lisa Tran",
      creatorID: 1
    },
    {
      name: "Virtual Book Club Meeting",
      startTime: "19:30:00",
      endTime: "21:00:00",
      startDate: "2024-06-05",
      endDate: "2024-06-05",
      description: "Online discussion of this month's selected novel",
      type: "Club Meeting",
      approved: "true",
      location: "Zoom",
      POCinfo: "Lisa Tran",
      creatorID: 1
    },
    {
      name: "Virtual Book Club Meeting",
      startTime: "19:30:00",
      endTime: "21:00:00",
      startDate: "2024-06-05",
      endDate: "2024-06-05",
      description: "Online discussion of this month's selected novel",
      type: "Club Meeting",
      approved: "true",
      location: "Zoom",
      POCinfo: "Lisa Tran",
      creatorID: 1
    },
    {
      name: "Mission Briefing",
      startTime: "15:30:00",
      endTime: "16:00:00",
      startDate: "2024-06-05",
      endDate: "2024-06-05",
      description: "SCI Briefing on current mission",
      type: "Official Briefing",
      approved: "true",
      location: "Zoom",
      POCinfo: "Johnny Knox-ville",
      creatorID: 1
    },
    {
      name: "Team Building Exercise",
      startTime: "09:00:00",
      endTime: "11:00:00",
      startDate: "2024-06-10",
      endDate: "2024-06-10",
      description: "Outdoor team building activities to improve collaboration",
      type: "Team Event",
      approved: "true",
      location: "Central Park",
      POCinfo: "Sarah Johnson",
      creatorID: 2
    },
    {
      name: "Quarterly Review Meeting",
      startTime: "13:00:00",
      endTime: "15:00:00",
      startDate: "2024-06-15",
      endDate: "2024-06-15",
      description: "Review of Q2 performance and goal setting for Q3",
      type: "Business Meeting",
      approved: "true",
      location: "Conference Room A",
      POCinfo: "Michael Chen",
      creatorID: 3
    },
    {
      name: "New Product Launch",
      startTime: "10:00:00",
      endTime: "12:30:00",
      startDate: "2024-06-20",
      endDate: "2024-06-20",
      description: "Unveiling of our newest product line to stakeholders",
      type: "Marketing Event",
      approved: "true",
      location: "Main Auditorium",
      POCinfo: "Emily Rodriguez",
      creatorID: 4
    },
    {
      name: "IT Security Training",
      startTime: "14:00:00",
      endTime: "16:00:00",
      startDate: "2024-06-25",
      endDate: "2024-06-25",
      description: "Mandatory cybersecurity awareness training for all employees",
      type: "Training Session",
      approved: "true",
      location: "Online Webinar",
      POCinfo: "Alex Patel",
      creatorID: 5
    },
    {
      name: "Project Alpha Kickoff",
      startTime: "09:30:00",
      endTime: "11:30:00",
      startDate: "2024-07-01",
      endDate: "2024-07-01",
      description: "Initial meeting to launch Project Alpha",
      type: "Project Meeting",
      approved: "true",
      location: "Meeting Room 3B",
      POCinfo: "Lisa Thompson",
      creatorID: 6
    },
    {
      name: "Annual Company Picnic",
      startTime: "12:00:00",
      endTime: "17:00:00",
      startDate: "2024-07-04",
      endDate: "2024-07-04",
      description: "Yearly outdoor event for employees and their families",
      type: "Social Event",
      approved: "true",
      location: "Riverside Park",
      POCinfo: "David Wilson",
      creatorID: 7
    },
    {
      name: "Budget Planning Session",
      startTime: "10:00:00",
      endTime: "12:00:00",
      startDate: "2024-07-10",
      endDate: "2024-07-10",
      description: "Financial planning for the upcoming fiscal year",
      type: "Finance Meeting",
      approved: "true",
      location: "CFO's Office",
      POCinfo: "Jennifer Lee",
      creatorID: 8
    },
    {
      name: "Customer Feedback Workshop",
      startTime: "13:30:00",
      endTime: "15:30:00",
      startDate: "2024-07-15",
      endDate: "2024-07-15",
      description: "Analysis of recent customer surveys and feedback",
      type: "Workshop",
      approved: "true",
      location: "Innovation Lab",
      POCinfo: "Robert Brown",
      creatorID: 9
    },
    {
      name: "Agile Methodology Training",
      startTime: "09:00:00",
      endTime: "17:00:00",
      startDate: "2024-07-20",
      endDate: "2024-07-21",
      description: "Two-day intensive training on Agile project management",
      type: "Training Course",
      approved: "true",
      location: "Training Center",
      POCinfo: "Samantha Wright",
      creatorID: 10
    },
    {
      name: "Vendor Negotiation Meeting",
      startTime: "11:00:00",
      endTime: "13:00:00",
      startDate: "2024-07-25",
      endDate: "2024-07-25",
      description: "Contract renegotiation with key suppliers",
      type: "Business Meeting",
      approved: "true",
      location: "Board Room",
      POCinfo: "Thomas Garcia",
      creatorID: 9
    },
    {
      name: "Employee Wellness Seminar",
      startTime: "14:00:00",
      endTime: "15:30:00",
      startDate: "2024-08-01",
      endDate: "2024-08-01",
      description: "Seminar on maintaining work-life balance and mental health",
      type: "Wellness Event",
      approved: "true",
      location: "Auditorium B",
      POCinfo: "Dr. Rachel Green",
      creatorID: 8
    },
    {
      name: "Emergency Response Drill",
      startTime: "10:30:00",
      endTime: "11:30:00",
      startDate: "2024-08-05",
      endDate: "2024-08-05",
      description: "Company-wide emergency evacuation practice",
      type: "Safety Drill",
      approved: "true",
      location: "All Office Locations",
      POCinfo: "Mark Stevens",
      creatorID: 7
    },
    {
      name: "Innovation Hackathon",
      startTime: "09:00:00",
      endTime: "18:00:00",
      startDate: "2024-08-10",
      endDate: "2024-08-11",
      description: "48-hour event to develop innovative solutions",
      type: "Development Event",
      approved: "true",
      location: "Tech Hub",
      POCinfo: "Laura Martinez",
      creatorID: 6
    },
    {
      name: "Quarterly All-Hands Meeting",
      startTime: "15:00:00",
      endTime: "17:00:00",
      startDate: "2024-08-15",
      endDate: "2024-08-15",
      description: "Company-wide update on quarterly performance and future plans",
      type: "Company Meeting",
      approved: "true",
      location: "Main Hall & Live Stream",
      POCinfo: "CEO's Office",
      creatorID: 7
    },
    {
      name: "Diversity and Inclusion Workshop",
      startTime: "13:00:00",
      endTime: "16:00:00",
      startDate: "2024-08-20",
      endDate: "2024-08-20",
      description: "Interactive workshop promoting workplace diversity and inclusion",
      type: "Training Workshop",
      approved: "true",
      location: "Conference Room C",
      POCinfo: "Olivia Taylor",
      creatorID: 4
    }
  ]);
};
