/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('positions').del()
  await knex('positions').insert([
    {name: 'Bearer', events_id: 2, users_id: 2},
    {name: 'Drill', events_id: 2, users_id: 1},
    {name: 'Firing Party', events_id: 1, users_id: 2},
    {name: 'Bearer', events_id: 2, users_id: 2},
    {name: 'Drill', events_id: 2, users_id: 1},
    {name: 'Firing Party', events_id: 1, users_id: 2},
    {name: 'Color Guard', events_id: 3, users_id: 4},
    {name: 'Bugler', events_id: 1, users_id: 3},
    {name: 'Escort', events_id: 4, users_id: 5},
    {name: 'Pallbearer', events_id: 5, users_id: 6},
    {name: 'Flag Folder', events_id: 3, users_id: 7},
    {name: 'Officer in Charge', events_id: 4, users_id: 8},
    {name: 'NCOIC', events_id: 5, users_id: 9},
    { name: 'Engineer', events_id: 12, users_id: 7 },
    { name: 'Designer', events_id: 5, users_id: 1 },
    { name: 'Manager', events_id: 22, users_id: 9 },
    { name: 'Analyst', events_id: 17, users_id: 2 },
    { name: 'Developer', events_id: 3, users_id: 4 },
    { name: 'Consultant', events_id: 10, users_id: 6 },
    { name: 'Coordinator', events_id: 25, users_id: 8 },
    { name: 'Architect', events_id: 14, users_id: 3 },
    { name: 'Technician', events_id: 8, users_id: 10 },
    { name: 'Specialist', events_id: 19, users_id: 5 },
    { name: 'Administrator', events_id: 7, users_id: 4 },
    { name: 'Planner', events_id: 23, users_id: 2 },
    { name: 'Supervisor', events_id: 2, users_id: 9 },
    { name: 'Strategist', events_id: 16, users_id: 7 },
    { name: 'Director', events_id: 21, users_id: 3 },
    { name: 'Executive', events_id: 11, users_id: 1 },
    { name: 'Producer', events_id: 6, users_id: 4 },
    { name: 'Consultant', events_id: 9, users_id: 6 },
    { name: 'Trainer', events_id: 15, users_id: 8 },
    { name: 'Advisor', events_id: 18, users_id: 5 },
    { name: 'Officer', events_id: 26, users_id: 10 },
    { name: 'Leader', events_id: 4, users_id: 2 },
    { name: 'Coordinator', events_id: 20, users_id: 7 },
    { name: 'Instructor', events_id: 13, users_id: 9 },
    { name: 'Auditor', events_id: 1, users_id: 3 },
    { name: 'Planner', events_id: 24, users_id: 6 },
    { name: 'Technician', events_id: 27, users_id: 5 },
    { name: 'Consultant', events_id: 8, users_id: 4 },
    { name: 'Strategist', events_id: 15, users_id: 1 },
    { name: 'Producer', events_id: 3, users_id: 2 },
    { name: 'Engineer', events_id: 12, users_id: 7 },
    { name: 'Designer', events_id: 12, users_id: 7 },
    { name: 'Manager', events_id: 22, users_id: 9 },
    { name: 'Analyst', events_id: 22, users_id: 9 },
    { name: 'Developer', events_id: 17, users_id: 2 },
    { name: 'Consultant', events_id: 17, users_id: 2 },
    { name: 'Coordinator', events_id: 25, users_id: 8 },
    { name: 'Architect', events_id: 25, users_id: 8 },
    { name: 'Technician', events_id: 14, users_id: 3 },
    { name: 'Specialist', events_id: 14, users_id: 3 },
    { name: 'Administrator', events_id: 19, users_id: 5 },
    { name: 'Planner', events_id: 19, users_id: 5 },
    { name: 'Supervisor', events_id: 2, users_id: 9 },
    { name: 'Strategist', events_id: 2, users_id: 9 },
    { name: 'Director', events_id: 21, users_id: 3 },
    { name: 'Executive', events_id: 21, users_id: 3 },
    { name: 'Producer', events_id: 11, users_id: 1 },
    { name: 'Consultant', events_id: 11, users_id: 1 },
    { name: 'Trainer', events_id: 6, users_id: 4 },
    { name: 'Advisor', events_id: 6, users_id: 4 },
    { name: 'Officer', events_id: 26, users_id: 10 },
    { name: 'Leader', events_id: 26, users_id: 10 },
    { name: 'Coordinator', events_id: 20, users_id: 7 },
    { name: 'Instructor', events_id: 20, users_id: 7 },
    { name: 'Auditor', events_id: 1, users_id: 3 },
    { name: 'Planner', events_id: 1, users_id: 3 },
    { name: 'Technician', events_id: 27, users_id: 5 },
    { name: 'Consultant', events_id: 27, users_id: 5 },
    { name: 'Strategist', events_id: 8, users_id: 4 },
    { name: 'Producer', events_id: 8, users_id: 4 }

  ])}
